import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SidePicture from "@/Components/SidePicture";
import RightSideBar from "@/Components/RightSideBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gray11"  >
      <body className={inter.className}>
        <div className="relative">
          <SidePicture/>
          <RightSideBar/>
        </div>
        {children}
        </body>
    </html>
  );
}
